### ISSUE TITLE
Ungültiger Index

### ISSUE THREAD

**Issue by DamoTheKing** [GymnasiumEverstenOldenburg/ADT-Implementierungen#14]
![grafik](https://github.com/GymnasiumEverstenOldenburg/ADT-Implementierungen/assets/168102835/a6bda664-9797-464d-b974-97a806ec0980)
![grafik](https://github.com/GymnasiumEverstenOldenburg/ADT-Implementierungen/assets/168102835/c1d53a30-7343-47e8-b4c2-d5cc23298e4a)
Wenn ein Item bei Index 0 ins DynArray eingefügt wird, kommt der Fehler "Ungültiger Index". Das passiert auch bei Index 1, 2, 5 und -1

**Comment by GelbEinhalb** [comment]
Sieht auf den ersten Blick ungewollt aus. Werde ich mir später genauer angucken :)
