### ISSUE TITLE
Set up Maven

### ISSUE THREAD

**Issue by Alexander-Reimer** [GymnasiumEverstenOldenburg/ADT-Implementierungen#3]
Setting up Maven for this project to make running tests automatically using Github Actions possible.
Also see:
- https://www.linkedin.com/pulse/testing-java-apps-junit-github-actions-emad-mohamed
- https://octopus.com/blog/githubactions-running-unit-tests

**Comment by GelbEinhalb** [comment]
Also set JUnit as dependency
