### ISSUE TITLE
Copy Java Files To BlueJ Project fails

### ISSUE THREAD

**Issue by GelbEinhalb** [GymnasiumEverstenOldenburg/ADT-Implementierungen#37]
```
Run git config user.name github-actions
HEAD detached at 2024.10.02
nothing to commit, working tree clean
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 1[28](https://github.com/GymnasiumEverstenOldenburg/ADT-Implementierungen/actions/runs/11141199763/job/30961583748#step:3:29).
```

**Comment by Alexander-Reimer** [comment]
https://github.com/GymnasiumEverstenOldenburg/ADT-Implementierungen/actions/runs/11141199763

**Comment by Alexander-Reimer** [comment]
According to the above, the action was triggered by the commit 7418002c438fc867f58212263eff00f5976661e9

**Comment by Alexander-Reimer** [comment]
The workflow triggers on push when files under `src/main/java/` are changed (see https://github.com/GymnasiumEverstenOldenburg/ADT-Implementierungen/actions/runs/11141199763/workflow), but 7418002 only modified projects/.compressed/project-files-bluej.zip

**Comment by Alexander-Reimer** [comment]
Syntax seems to be correct (cf. https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files)
